version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:860061945305:task-definition/pensioner-detail-service-narendra:1"
        LoadBalancerInfo:
          ContainerName: "pensioner-detail-service"
          ContainerPort: "8083"
        PlatformVersion: "LATEST"